'use client'

// AI Executive Summary section — renders the AI-generated narrative.
//
// Behavior:
//   - On mount: if description_html is empty, auto-fires the generate route.
//   - Read-only display by default with "Edit" button.
//   - Clicking "Edit" enters a <textarea> in-place.
//   - "Save" persists the edited text via server action.
//   - "Regenerate" re-calls the AI route and replaces textarea content on success.
//   - [UNVERIFIED] sentences are highlighted in amber in read-only mode.
//   - Footer line: "Generated by AI — please review before sending."
//
// PHASE2-TIPTAP: The textarea edit surface is deferred. Sprint 3 replaces this
// with a Tiptap inline editor. The component structure stays — only the edit
// surface changes. Mark the textarea container below.

import { useState, useEffect, useTransition, useRef } from 'react'

interface AIExecutiveSummarySectionProps {
  reportId: number
  sectionId: number
  blockId: number
  /** Current persisted text from description_html. Empty string if not yet generated. */
  initialText: string
  title?: string
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Split text into segments, wrapping [UNVERIFIED]-prefixed sentences in an amber
 *  highlight. Operates on plain text, not HTML. Matches [UNVERIFIED] at the
 *  start of a sentence (after a period+space or at the very start of text). */
function renderWithUnverifiedHighlights(text: string): React.ReactNode[] {
  if (!text.includes('[UNVERIFIED]')) {
    return [<span key="plain">{text}</span>]
  }

  // Split on sentence boundaries then re-attach [UNVERIFIED] to the sentence
  // it belongs to. Strategy: split on the [UNVERIFIED] token itself, then
  // split surrounding text on ". " boundaries so clean sentences stay plain.
  const parts = text.split(/(\[UNVERIFIED\][^.!?]*[.!?]?)/)
  return parts.map((part, i) => {
    if (part.startsWith('[UNVERIFIED]')) {
      return (
        <mark
          key={i}
          className="bg-amber-100 text-amber-900 px-0.5 rounded-sm"
          title="This sentence may contain a number not in the source data. Review before sending."
        >
          {part}
        </mark>
      )
    }
    return <span key={i}>{part}</span>
  })
}

// ─── Server action (inline — Next.js 16 allows 'use server' in client components
//     when the action is defined in a separate file or passed as prop. We use a
//     fetch call to the REST API instead to keep the client component self-contained.) ─

async function persistSummaryText(args: {
  reportId: number
  sectionId: number
  blockId: number
  text: string
}): Promise<{ ok: boolean; error?: string }> {
  const res = await fetch(`/api/platform/reports/${args.reportId}/ai-summary`, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      sectionId: args.sectionId,
      blockId: args.blockId,
      text: args.text,
    }),
  })
  if (!res.ok) {
    const data = await res.json().catch(() => ({})) as { error?: string }
    return { ok: false, error: data.error || 'Save failed' }
  }
  return { ok: true }
}

async function generateSummary(reportId: number): Promise<{
  ok: boolean
  summaryText?: string
  generatedAt?: string
  error?: string
  isRateLimit?: boolean
}> {
  const res = await fetch(`/api/platform/reports/${reportId}/ai-summary`, {
    method: 'POST',
  })
  const data = await res.json().catch(() => ({})) as {
    ok?: boolean
    summaryText?: string
    generatedAt?: string
    error?: string
    retryAfterSeconds?: number
  }
  if (res.status === 429) {
    return {
      ok: false,
      error: data.error || 'Rate limited — please wait before regenerating.',
      isRateLimit: true,
    }
  }
  if (!res.ok) {
    return { ok: false, error: data.error || 'Generation failed' }
  }
  return { ok: true, summaryText: data.summaryText, generatedAt: data.generatedAt }
}

// ─── Component ────────────────────────────────────────────────────────────────

export function AIExecutiveSummarySection({
  reportId,
  sectionId,
  blockId,
  initialText,
  title = 'Executive Summary',
}: AIExecutiveSummarySectionProps) {
  const [text, setText] = useState(initialText)
  const [editText, setEditText] = useState(initialText)
  const [isEditing, setIsEditing] = useState(false)
  const [isGenerating, setIsGenerating] = useState(false)
  const [isSaving, setIsSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [generatedAt, setGeneratedAt] = useState<string | null>(null)
  const [autoFired, setAutoFired] = useState(false)
  const textareaRef = useRef<HTMLTextAreaElement>(null)

  // Auto-fire generation on first mount if description_html is empty.
  useEffect(() => {
    if (!text.trim() && !autoFired) {
      setAutoFired(true)
      setIsGenerating(true)
      setError(null)
      generateSummary(reportId).then((result) => {
        setIsGenerating(false)
        if (result.ok && result.summaryText) {
          setText(result.summaryText)
          setEditText(result.summaryText)
          if (result.generatedAt) setGeneratedAt(result.generatedAt)
        } else {
          setError(result.error ?? 'Generation failed — click Regenerate to retry.')
        }
      })
    }
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  // Focus textarea when edit mode starts.
  useEffect(() => {
    if (isEditing && textareaRef.current) {
      textareaRef.current.focus()
      // Place cursor at end.
      const len = textareaRef.current.value.length
      textareaRef.current.setSelectionRange(len, len)
    }
  }, [isEditing])

  function handleEdit() {
    setEditText(text)
    setIsEditing(true)
    setError(null)
  }

  function handleCancelEdit() {
    setIsEditing(false)
    setEditText(text)
  }

  async function handleSave() {
    const trimmed = editText.trim()
    if (!trimmed) return
    setIsSaving(true)
    setError(null)
    const result = await persistSummaryText({
      reportId,
      sectionId,
      blockId,
      text: trimmed,
    })
    setIsSaving(false)
    if (result.ok) {
      setText(trimmed)
      setIsEditing(false)
    } else {
      setError(result.error ?? 'Save failed')
    }
  }

  async function handleRegenerate() {
    setIsGenerating(true)
    setError(null)
    const result = await generateSummary(reportId)
    setIsGenerating(false)
    if (result.ok && result.summaryText) {
      setText(result.summaryText)
      setEditText(result.summaryText)
      if (result.generatedAt) setGeneratedAt(result.generatedAt)
      // If currently editing, refresh the textarea content.
      if (isEditing) {
        setEditText(result.summaryText)
      }
    } else {
      setError(result.error ?? 'Regeneration failed')
    }
  }

  const formattedGeneratedAt = generatedAt
    ? new Date(generatedAt).toLocaleString('en-US', {
        month: 'short',
        day: 'numeric',
        hour: 'numeric',
        minute: '2-digit',
      })
    : null

  return (
    // PHASE2-TIPTAP: replace outer section with <TiptapSectionNode> custom extension
    <section className="mb-10">
      {/* Section header */}
      <div className="flex items-start justify-between mb-3 gap-4">
        <h2 className="text-xl font-semibold text-gray-900">{title}</h2>
        <div data-summary-actions className="flex items-center gap-2 flex-shrink-0">
          {/* Regenerate button */}
          <button
            onClick={handleRegenerate}
            disabled={isGenerating || isSaving}
            className="text-xs font-medium text-gray-500 hover:text-gray-700 border border-gray-200 hover:border-gray-300 px-2.5 py-1 rounded-md transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-1.5"
            title="Regenerate AI summary from current report data"
          >
            {isGenerating ? (
              <>
                <span className="w-3 h-3 border border-gray-400/30 border-t-gray-500 rounded-full animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                    d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                </svg>
                Regenerate
              </>
            )}
          </button>

          {/* Edit / Save / Cancel buttons */}
          {!isEditing ? (
            <button
              onClick={handleEdit}
              disabled={isGenerating}
              className="text-xs font-medium text-blue-600 hover:text-blue-700 border border-blue-200 hover:border-blue-300 px-2.5 py-1 rounded-md transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Edit
            </button>
          ) : (
            <>
              <button
                onClick={handleCancelEdit}
                disabled={isSaving}
                className="text-xs font-medium text-gray-500 hover:text-gray-700 border border-gray-200 px-2.5 py-1 rounded-md transition-colors disabled:opacity-50"
              >
                Cancel
              </button>
              <button
                onClick={handleSave}
                disabled={isSaving || !editText.trim()}
                className="text-xs font-medium text-white bg-blue-600 hover:bg-blue-700 disabled:bg-blue-300 px-2.5 py-1 rounded-md transition-colors flex items-center gap-1.5"
              >
                {isSaving ? (
                  <>
                    <span className="w-3 h-3 border border-white/30 border-t-white rounded-full animate-spin" />
                    Saving...
                  </>
                ) : (
                  'Save'
                )}
              </button>
            </>
          )}
        </div>
      </div>

      {/* Error banner */}
      {error && (
        <div className="bg-red-50 border border-red-200 rounded-lg px-4 py-3 mb-4 text-sm text-red-700">
          {error}
        </div>
      )}

      {/* Generating skeleton */}
      {isGenerating && !text && (
        <div className="bg-white rounded-lg border border-gray-200 p-6">
          <div className="space-y-2.5">
            <div className="h-4 bg-gray-100 rounded animate-pulse w-full" />
            <div className="h-4 bg-gray-100 rounded animate-pulse w-5/6" />
            <div className="h-4 bg-gray-100 rounded animate-pulse w-4/6" />
          </div>
        </div>
      )}

      {/* Read-only display with [UNVERIFIED] highlights */}
      {!isEditing && (text || (!isGenerating && !error)) && (
        // PHASE2-TIPTAP: description_html div — Sprint 3 replaces with Tiptap viewer
        <div className="bg-white rounded-lg border border-gray-200 p-6">
          {text ? (
            <p className="text-sm text-gray-700 leading-relaxed">
              {renderWithUnverifiedHighlights(text)}
            </p>
          ) : (
            <p className="text-sm text-gray-400 italic">
              Summary not yet generated.
            </p>
          )}
        </div>
      )}

      {/* Edit mode — textarea */}
      {isEditing && (
        // PHASE2-TIPTAP: replace this textarea + container with a Tiptap inline editor
        <div className="bg-white rounded-lg border border-blue-300 ring-1 ring-blue-200 p-6">
          <textarea
            ref={textareaRef}
            value={editText}
            onChange={(e) => setEditText(e.target.value)}
            rows={6}
            className="w-full text-sm text-gray-700 leading-relaxed resize-y border-0 outline-none focus:ring-0 bg-transparent placeholder-gray-400"
            placeholder="Enter the executive summary text..."
            disabled={isSaving}
          />
          <p className="text-xs text-gray-400 mt-2">
            Remove or rewrite any sentence marked [UNVERIFIED] before saving.
          </p>
        </div>
      )}

      {/* Footer */}
      <div className="flex items-center justify-between mt-3">
        <p className="text-xs text-gray-400">
          Generated by AI — please review before sending.
        </p>
        {formattedGeneratedAt && (
          <p className="text-xs text-gray-300">
            Last generated {formattedGeneratedAt}
          </p>
        )}
      </div>
    </section>
  )
}
