#!/usr/bin/env bash
#
# Motion Lite — dispatch bridge setup
# ------------------------------------
# Connects your local Mac (running Claude Code) to a Motion Lite server's
# dispatch queue. The bridge polls for queued jobs, runs `claude --print`
# with the prompt, and POSTs the result back.
#
# Run once: bash tools/bridge/setup.sh
# Re-run any time to reconfigure or reinstall the launchd job.
#

set -e

cd "$(dirname "$0")"
BRIDGE_DIR="$(pwd)"

echo ""
echo "Motion Lite — Dispatch Bridge Setup"
echo "===================================="
echo ""

# --- 1. Check prerequisites ---
if ! command -v claude >/dev/null 2>&1; then
  echo "ERROR: 'claude' CLI not found in PATH."
  echo "Install Claude Code first: https://docs.claude.com/claude-code"
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "ERROR: 'jq' not installed. Run: brew install jq"
  exit 1
fi

if ! command -v curl >/dev/null 2>&1; then
  echo "ERROR: 'curl' not found"
  exit 1
fi

# --- 2. Prompt for config (defaults from existing env file) ---
ENV_FILE="$BRIDGE_DIR/.env"
[ -f "$ENV_FILE" ] && source "$ENV_FILE"

DEFAULT_URL="${MOTION_URL:-http://localhost:4000}"
echo "Motion Lite server URL"
echo "  e.g. http://localhost:4000  or  https://your-app.example.com"
read -r -p "URL [$DEFAULT_URL]: " input_url
MOTION_URL="${input_url:-$DEFAULT_URL}"

DEFAULT_SECRET="${BRIDGE_SECRET:-}"
if [ -z "$DEFAULT_SECRET" ]; then
  DEFAULT_SECRET="$(openssl rand -hex 24)"
  echo ""
  echo "Generated a new BRIDGE_SECRET (you'll need to set this in your"
  echo "Motion Lite server's .env.local too)."
fi
echo ""
read -r -p "BRIDGE_SECRET [$DEFAULT_SECRET]: " input_secret
BRIDGE_SECRET="${input_secret:-$DEFAULT_SECRET}"

DEFAULT_POLL="${POLL_INTERVAL:-5}"
read -r -p "Poll interval seconds [$DEFAULT_POLL]: " input_poll
POLL_INTERVAL="${input_poll:-$DEFAULT_POLL}"

DEFAULT_WORKER="${WORKER_ID:-$(hostname -s)}"
read -r -p "Worker ID [$DEFAULT_WORKER]: " input_worker
WORKER_ID="${input_worker:-$DEFAULT_WORKER}"

# --- 3. Write .env ---
cat > "$ENV_FILE" <<EOF
# Generated by tools/bridge/setup.sh — re-run to change
MOTION_URL=$MOTION_URL
BRIDGE_SECRET=$BRIDGE_SECRET
POLL_INTERVAL=$POLL_INTERVAL
WORKER_ID=$WORKER_ID
EOF
chmod 600 "$ENV_FILE"
echo ""
echo "✓ Wrote $ENV_FILE"

# --- 4. Test the connection ---
echo ""
echo "Testing connection to $MOTION_URL ..."
status=$(curl -s -o /dev/null -w "%{http_code}" \
  -H "x-bridge-secret: $BRIDGE_SECRET" \
  -H "x-bridge-worker: $WORKER_ID" \
  "$MOTION_URL/api/dispatch/queue")

if [ "$status" = "200" ]; then
  echo "✓ Server reachable, BRIDGE_SECRET accepted"
else
  echo "✗ HTTP $status from $MOTION_URL/api/dispatch/queue"
  echo "  - Is Motion Lite running?"
  echo "  - Did you set BRIDGE_SECRET=$BRIDGE_SECRET in the server's .env.local and restart?"
  echo "  - For 401: secret mismatch. For 404: wrong URL."
  echo ""
  echo "Setup wrote .env anyway. Fix the server, then re-run setup or just"
  echo "run: bash tools/bridge/dispatch-bridge.sh"
fi

# --- 5. Install launchd job (macOS) ---
echo ""
read -r -p "Install as launchd service so it auto-starts on login? [y/N] " do_install
if [[ "$do_install" =~ ^[Yy]$ ]]; then
  PLIST="$HOME/Library/LaunchAgents/com.motionlite.dispatch-bridge.plist"
  cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.motionlite.dispatch-bridge</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>$BRIDGE_DIR/dispatch-bridge.sh</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>$BRIDGE_DIR/bridge.log</string>
  <key>StandardErrorPath</key>
  <string>$BRIDGE_DIR/bridge.log</string>
  <key>WorkingDirectory</key>
  <string>$BRIDGE_DIR</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
  </dict>
</dict>
</plist>
EOF
  launchctl unload "$PLIST" 2>/dev/null || true
  launchctl load "$PLIST"
  echo "✓ Installed launchd job: com.motionlite.dispatch-bridge"
  echo "  Log: $BRIDGE_DIR/bridge.log"
  echo "  Stop: launchctl unload $PLIST"
  echo "  Start: launchctl load $PLIST"
else
  echo ""
  echo "Skipped launchd. Run the bridge manually whenever you want it on:"
  echo "  bash $BRIDGE_DIR/dispatch-bridge.sh"
fi

echo ""
echo "Done. Server-side reminder:"
echo "  Add this line to Motion Lite's .env.local and restart:"
echo "    BRIDGE_SECRET=$BRIDGE_SECRET"
echo ""
